// ATLServerLib.idl: источник языка IDL для ATLServerLib
//

// Этот файл будет обработан средством MIDL для
// создание библиотеки типов ($handlersafeidlname$.tlb) и кода маршалирования.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(adcf96fe-86aa-4f7b-a7a5-95506e6a5628),
	version(1.0),
]
library ATLServerLibLib
{
	importlib("stdole2.tlb");
};

